title: old-radio's Blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "old-radio"
  email: "10albatross@gmail.com"
  url: "https://old-radio.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SomeHacker"
year : "2020"
